<?php
require_once dirname(__DIR__).'/app/helpers.php';
$token=preg_replace('/[^a-f0-9]/','',(string)($_GET['token']??''));
$playKey=trim((string)($_GET['play']??''));
if($playKey!==''){
 $st=db()->prepare("SELECT t.token FROM embed_tokens t WHERE t.play_key=? AND t.status=1 LIMIT 1");$st->execute([$playKey]);$token=(string)($st->fetchColumn()?:'');
}
if(!preg_match('/^[a-f0-9]{64}$/',$token)){http_response_code(404);exit('Invalid player token');}
$st=db()->prepare("SELECT v.*,t.id token_id,t.play_key FROM embed_tokens t JOIN videos v ON v.id=t.video_id WHERE t.token=? AND t.status=1 AND (t.expires_at IS NULL OR t.expires_at>NOW()) AND v.status='published' LIMIT 1");$st->execute([$token]);$v=$st->fetch();if(!$v){http_response_code(404);exit('Video unavailable');}
$ref=$_SERVER['HTTP_REFERER']??'';$host=strtolower(parse_url($ref,PHP_URL_HOST)?:'');
if($host){$ok=db()->prepare("SELECT id FROM allowed_domains WHERE status=1 AND (domain=? OR ? LIKE CONCAT('%.',domain)) LIMIT 1");$ok->execute([$host,$host]);if(!$ok->fetch()){http_response_code(403);exit('Embedding domain not allowed');}}
$ls=db()->prepare('SELECT id,label,url,requests,status FROM stream_links WHERE video_id=? AND status=1 ORDER BY sort_order,id');$ls->execute([$v['id']]);$streams=$ls->fetchAll();
if(!$streams){http_response_code(404);exit('No active player source');}
db()->prepare('UPDATE videos SET views=views+1 WHERE id=?')->execute([$v['id']]);
$publicKey=(string)($v['play_key']??'');
$initialUrl=$streams[0]['url'];
?><!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="referrer" content="origin-when-cross-origin"><title><?=e($v['title'])?></title><style>
:root{color-scheme:dark}*{box-sizing:border-box}html,body{margin:0;width:100%;height:100%;background:#05070a;font-family:Inter,system-ui,-apple-system,"Segoe UI",sans-serif;color:#fff}.multi-player{width:100%;height:100%;display:flex;flex-direction:column;background:#080b10}.toolbar{display:flex;align-items:center;gap:8px;min-height:50px;padding:7px 10px;background:linear-gradient(180deg,#151b25,#0f141c);border-bottom:1px solid #ffffff10;overflow:auto}.brand{font-size:12px;font-weight:700;opacity:.9;white-space:nowrap;max-width:30%;overflow:hidden;text-overflow:ellipsis}.host-list{display:flex;align-items:center;gap:7px;overflow:auto}.host-btn{border:1px solid #344256;background:#151d28;color:#cbd5e1;padding:7px 11px;border-radius:7px;font-size:12px;font-weight:650;cursor:pointer;white-space:nowrap}.host-btn:hover{background:#1d2735}.host-btn.active{background:#2563eb;border-color:#3b82f6;color:#fff;box-shadow:0 4px 13px #2563eb44}.toolbar-actions{margin-left:auto;display:flex;gap:6px}.tool-btn{border:1px solid #334155;background:#151d28;color:#cbd5e1;border-radius:7px;padding:7px 9px;font-size:12px;cursor:pointer;white-space:nowrap}.tool-btn:hover{background:#1d2735}.frame-wrap{position:relative;flex:1;min-height:0;background:#000}.frame-wrap iframe{width:100%;height:100%;border:0;display:block;background:#000}.loading{position:absolute;inset:0;z-index:2;display:grid;place-items:center;background:radial-gradient(circle at center,#151b24 0,#000 58%);color:#94a3b8;font-size:13px;pointer-events:none}.loading-box{display:flex;flex-direction:column;align-items:center;gap:10px}.spinner{width:28px;height:28px;border:3px solid #334155;border-top-color:#60a5fa;border-radius:50%;animation:spin .9s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}.hidden{display:none!important}.foot{min-height:29px;padding:6px 10px;background:#0b1017;color:#64748b;font-size:10px;display:flex;align-items:center}.foot .key{margin-left:auto;color:#475569}
</style></head><body><div class="multi-player"><div class="toolbar"><div class="brand" title="<?=e($v['title'])?>"><?=e($v['title'])?></div><div class="host-list"><?php foreach($streams as $i=>$s):?><button class="host-btn <?=$i===0?'active':''?>" data-source="<?=e(base64_encode($s['url']))?>"><?=e($s['label'])?></button><?php endforeach;?></div><div class="toolbar-actions"><button class="tool-btn" id="open-source">↗ Open</button><button class="tool-btn" id="fullscreen">⛶</button></div></div><div class="frame-wrap"><div id="loading" class="loading"><div class="loading-box"><div class="spinner"></div><div>Loading player…</div></div></div><iframe id="host-frame" src="<?=e($initialUrl)?>" allow="autoplay; fullscreen; picture-in-picture; encrypted-media" allowfullscreen referrerpolicy="origin-when-cross-origin"></iframe></div><div class="foot"><span>Multi-Host Player</span><span class="key"><?=e($publicKey)?></span></div></div>
<script>(function(){const frame=document.getElementById('host-frame'),load=document.getElementById('loading'),open=document.getElementById('open-source'),fs=document.getElementById('fullscreen');let current=<?=json_encode($initialUrl)?>;document.querySelectorAll('.host-btn').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.host-btn').forEach(b=>b.classList.remove('active'));btn.classList.add('active');try{current=atob(btn.dataset.source)}catch(e){current='about:blank'}load.classList.remove('hidden');frame.src=current;open.dataset.url=current;}));frame.addEventListener('load',()=>load.classList.add('hidden'));setTimeout(()=>load.classList.add('hidden'),7000);open.dataset.url=current;open.addEventListener('click',()=>{if(open.dataset.url)window.open(open.dataset.url,'_blank','noopener');});fs.addEventListener('click',()=>{const el=document.querySelector('.multi-player');if(document.fullscreenElement)document.exitFullscreen();else el.requestFullscreen?.();});})();</script></body></html>