<?php
require_once __DIR__.'/_header.php';
$id=(int)($_GET['id']??0);$st=db()->prepare('SELECT * FROM ad_campaigns WHERE id=?');$st->execute([$id]);$a=$st->fetch();if(!$a){http_response_code(404);exit('Campaign not found');}
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();
 $network=in_array($_POST['network']??'', ['adsterra','clickadu','custom'],true)?$_POST['network']:'custom';
 $type=in_array($_POST['ad_type']??'', ['javascript','html','external'],true)?$_POST['ad_type']:'javascript';
 $trigger=in_array($_POST['trigger_event']??'', ['player_load','player_click','video_start','video_end','manual'],true)?$_POST['trigger_event']:'player_click';
 db()->prepare('UPDATE ad_campaigns SET name=?,network=?,ad_type=?,ad_code=?,status=?,priority=?,weight=?,frequency_minutes=?,trigger_event=? WHERE id=?')->execute([trim($_POST['name']),$network,$type,$_POST['ad_code']??'',isset($_POST['status'])?1:0,(int)$_POST['priority'],max(1,(int)$_POST['weight']),(int)$_POST['frequency_minutes'],$trigger,$id]);
 log_action('ad.update','campaign_id='.$id); header('Location: ads.php');exit;
}
?><div class="page-head"><div><h1>Edit Advertisement</h1><p>Update campaign, JavaScript code and rotation rules.</p></div></div><form method="post" class="panel" style="padding:22px"><?=csrf_field()?><label>Name<input name="name" value="<?=e($a['name'])?>" required></label><div class="grid"><label>Network<select name="network"><?php foreach(['adsterra','clickadu','custom'] as $n):?><option value="<?=$n?>" <?=$a['network']===$n?'selected':''?>><?=ucfirst($n)?></option><?php endforeach;?></select></label><label>Type<select name="ad_type"><?php foreach(['javascript','html','external'] as $n):?><option value="<?=$n?>" <?=$a['ad_type']===$n?'selected':''?>><?=ucfirst($n)?></option><?php endforeach;?></select></label><label>Trigger<select name="trigger_event"><?php foreach(['player_load','player_click','video_start','video_end','manual'] as $n):?><option value="<?=$n?>" <?=$a['trigger_event']===$n?'selected':''?>><?=ucwords(str_replace('_',' ',$n))?></option><?php endforeach;?></select></label></div><label>Ad JavaScript / Code<textarea name="ad_code" rows="10"><?=e($a['ad_code'])?></textarea></label><div class="grid"><label>Priority<input type="number" name="priority" value="<?=$a['priority']?>"></label><label>Weight<input type="number" name="weight" min="1" value="<?=$a['weight']?>"></label><label>Cooldown (minutes)<input type="number" name="frequency_minutes" min="0" value="<?=$a['frequency_minutes']?>"></label></div><label class="check"><input type="checkbox" name="status" <?=$a['status']?'checked':''?>> Active</label><button>Save Changes</button> <a class="button secondary" href="ads.php">Cancel</a></form><?php require __DIR__.'/_footer.php';