<?php
require_once __DIR__.'/_header.php';
if($_SERVER['REQUEST_METHOD']==='POST'){
 verify_csrf();
 $network=in_array($_POST['network']??'', ['adsterra','clickadu','custom'],true)?$_POST['network']:'custom';
 $type=in_array($_POST['ad_type']??'', ['javascript','html','external'],true)?$_POST['ad_type']:'javascript';
 $trigger=in_array($_POST['trigger_event']??'', ['player_load','player_click','video_start','video_end','manual'],true)?$_POST['trigger_event']:'player_click';
 db()->prepare('INSERT INTO ad_campaigns(name,network,ad_type,ad_code,status,priority,weight,frequency_minutes,trigger_event) VALUES(?,?,?,?,?,?,?,?,?)')->execute([trim($_POST['name']),$network,$type,$_POST['ad_code']??'',isset($_POST['status'])?1:0,(int)$_POST['priority'],max(1,(int)$_POST['weight']),(int)$_POST['frequency_minutes'],$trigger]);
 log_action('ad.create','network='.$network);
}
$rows=db()->query('SELECT * FROM ad_campaigns ORDER BY priority DESC,id DESC')->fetchAll();
?>
<div class="page-head"><div><h1>Advertisements</h1><p>Manage JavaScript campaigns and automatic rotation.</p></div></div>
<div class="panel" style="padding:22px"><h2>Add Campaign</h2><form method="post"><?=csrf_field()?><div class="grid"><label>Name<input name="name" placeholder="Adsterra Popup" required></label><label>Network<select name="network"><option value="adsterra">Adsterra</option><option value="clickadu">Clickadu</option><option value="custom">Custom</option></select></label><label>Type<select name="ad_type"><option value="javascript">JavaScript</option><option value="html">HTML</option><option value="external">External Script</option></select></label></div><label>JavaScript / Ad Code<textarea name="ad_code" rows="7" placeholder="Paste the publisher JavaScript snippet here."></textarea></label><div class="grid"><label>Trigger<select name="trigger_event"><option value="player_click">Player click</option><option value="player_load">Player load</option><option value="video_start">Video start</option><option value="video_end">Video end</option><option value="manual">Manual</option></select></label><label>Priority<input type="number" name="priority" value="1"></label><label>Weight<input type="number" name="weight" value="100" min="1"></label></div><label>Cooldown (minutes)<input type="number" name="frequency_minutes" value="30" min="0"></label><label class="check"><input type="checkbox" name="status" checked> Active</label><button>Add Campaign</button></form></div>
<div class="panel"><div class="panel-head"><h2>Active Campaigns</h2><span class="select-like">Priority + Weight Rotation</span></div><div class="table-wrap"><table><thead><tr><th>Name</th><th>Network</th><th>Type</th><th>Status</th><th>Priority</th><th>Weight</th><th>Cooldown</th><th>Actions</th></tr></thead><tbody><?php foreach($rows as $r):?><tr><td><b><?=e($r['name'])?></b></td><td><?=e(ucfirst($r['network']))?></td><td><?=e(ucfirst($r['ad_type']))?></td><td><span class="badge <?=$r['status']?'published':'private'?>"><?=$r['status']?'Active':'Off'?></span></td><td><?=$r['priority']?></td><td><?=$r['weight']?></td><td><?=$r['frequency_minutes']?>m</td><td class="actions"><a href="ad-edit.php?id=<?=$r['id']?>">✎ Edit</a><form method="post" action="ad-delete.php" style="display:inline"><?=csrf_field()?><input type="hidden" name="id" value="<?=$r['id']?>"><button class="danger link-button" onclick="return confirm('Delete this campaign?')">Delete</button></form></td></tr><?php endforeach;?><?php if(!$rows):?><tr><td colspan="8" class="empty">No campaigns configured.</td></tr><?php endif;?></tbody></table></div></div>
<div class="panel" style="padding:22px"><div class="panel-head"><h2>Publisher Earnings</h2><span class="select-like" id="stats-period">Current month</span></div><div class="earnings-grid"><div><small>Adsterra</small><strong id="adsterra-earnings">—</strong></div><div><small>Clickadu</small><strong id="clickadu-earnings">—</strong></div><div><small>Total</small><strong id="total-earnings">—</strong></div></div><p class="muted">Revenue comes from the publisher APIs, not local event estimates.</p></div>
<script>fetch('<?=e(app_url('api/network-stats.php'))?>').then(r=>r.json()).then(x=>{const f=n=>'$'+Number(n||0).toFixed(4);document.getElementById('adsterra-earnings').textContent=f(x.networks[0]?.revenue);document.getElementById('clickadu-earnings').textContent=f(x.networks[1]?.revenue);document.getElementById('total-earnings').textContent=f(x.total_revenue)}).catch(()=>{});</script>
<?php require __DIR__.'/_footer.php';